// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: CitySearch.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CitySearchService_Search_FullMethodName = "/proto.CitySearchService/Search"
)

// CitySearchServiceClient is the client API for CitySearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CitySearchServiceClient interface {
	Search(ctx context.Context, in *CitySearchRequest, opts ...grpc.CallOption) (*CitySearchResponse, error)
}

type citySearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCitySearchServiceClient(cc grpc.ClientConnInterface) CitySearchServiceClient {
	return &citySearchServiceClient{cc}
}

func (c *citySearchServiceClient) Search(ctx context.Context, in *CitySearchRequest, opts ...grpc.CallOption) (*CitySearchResponse, error) {
	out := new(CitySearchResponse)
	err := c.cc.Invoke(ctx, CitySearchService_Search_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CitySearchServiceServer is the server API for CitySearchService service.
// All implementations must embed UnimplementedCitySearchServiceServer
// for forward compatibility
type CitySearchServiceServer interface {
	Search(context.Context, *CitySearchRequest) (*CitySearchResponse, error)
	mustEmbedUnimplementedCitySearchServiceServer()
}

// UnimplementedCitySearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCitySearchServiceServer struct {
}

func (UnimplementedCitySearchServiceServer) Search(context.Context, *CitySearchRequest) (*CitySearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedCitySearchServiceServer) mustEmbedUnimplementedCitySearchServiceServer() {}

// UnsafeCitySearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CitySearchServiceServer will
// result in compilation errors.
type UnsafeCitySearchServiceServer interface {
	mustEmbedUnimplementedCitySearchServiceServer()
}

func RegisterCitySearchServiceServer(s grpc.ServiceRegistrar, srv CitySearchServiceServer) {
	s.RegisterService(&CitySearchService_ServiceDesc, srv)
}

func _CitySearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CitySearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CitySearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CitySearchService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CitySearchServiceServer).Search(ctx, req.(*CitySearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CitySearchService_ServiceDesc is the grpc.ServiceDesc for CitySearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CitySearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CitySearchService",
	HandlerType: (*CitySearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _CitySearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CitySearch.proto",
}
